# Default configuration for CosmicPINN

trainer:
  epochs: 5000
  lr: 1e-3
  device: "cpu"  # or "cpu"
  checkpoint_every: 500  # iterations
  print_every: 100

network:
  layers: [3, 64, 64, 64, 64, 4]  # input=3 (t,x,y); output=4 (delta,u,v,phi)
  activation: tanh

physics:
  domain:
    t_min: 0.0
    t_max: 1.0
    x_min: -1.0
    x_max: 1.0
    y_min: -1.0
    y_max: 1.0

  initial_conditions:
    type: gaussian  # currently only gaussian
    amplitude: 0.1
    sigma: 0.2
    center: [0.0, 0.0]

data:
  n_collocation: 10000  # interior points per epoch
  n_initial: 1024       # points on t=0 plane enforcing ICs 